version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - D:/docker-data/mysql:/var/lib/mysql
    networks:
      - my_network

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - D:/docker-data/redis:/data
    networks:
      - my_network

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - D:/docker-data/nginx/html/dist:/usr/share/nginx/html  # 挂载 dist 目录
      - D:/docker-data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf  # 挂载 nginx.conf 文件
    networks:
      - my_network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  my_network:
    driver: bridge
